// @kogane/read-model: the explicit read repository of the evidence browser.
// New queries go through ObservationReader; nothing rewrites SQL strings.

export {
  activeStateProjection,
  completeSnapshotCandidates,
  economicallySummable,
  evidenceExists,
  isObservationKind,
  legacyPublishedParses,
  OBSERVATION_TABLES,
  type ObservationKind,
  type ObservationTable,
  publishedParses,
  recordedParses,
  SNAPSHOT_RELATIONS,
  snapshotAdoptable,
  snapshotPolicyComparison,
  successfulFetchRuns,
  successfulParses,
  unitParseable,
  visibleEvidence,
} from "./concepts";
export {
  CANDIDATE_LIMIT,
  type CollectionScope,
  type MeasureView,
  ORDER_KEYS,
  type OrderKey,
  PAGE_LIMIT,
  type PageLimit,
  type PageSql,
  pagedCollection,
  periodMeasureSql,
  type Predicates,
  RESULT_BOUND,
  SCOPE_COLUMNS,
  type ScopeKey,
  scopePredicates,
} from "./scope";
export { parseWarnings, summarize } from "./mappers";
export {
  type ArtifactQuery,
  type BalanceHistoryQuery,
  type FilterOptionsKind,
  type FilterOptionsQuery,
  type LatestBalanceQuery,
  type ObservationReader,
  type ObservationReference,
  type ParsingHealth,
  type PositionQuery,
  type RawDownload,
  type RawDownloadReference,
  type ReaderOptions,
  ResultLimitExceededError,
  type SqlExecutor,
  type TransactionQuery,
} from "./reader";
export { createObservationReader } from "./observation-reader";
export { createD1ObservationReader, d1Executor, type D1Like } from "./d1";
export {
  DECIMAL_POLICY_RELEASE,
  DEFAULT_IDENTITY_READ_MODE,
  IDENTITY_READ_MODES,
  type IdentityReadMode,
  type InterpretationContext,
  identityReleaseFor,
  interpretationContext,
  isIdentityReadMode,
  LATEST_IDENTITY_RELEASE,
  MAPPING_RELATIONS,
  MEASURE_POLICY_RELEASE,
  NO_RECORDED_IDENTITY_RELEASE,
} from "./identity";
export { organizationSql, PRODUCT_METADATA_LIMIT } from "./organization";
export {
  AUTHORITY_POLICY,
  AUTHORITY_POLICY_RELEASE,
  AUTHORITY_RANKS,
  type AuthorityRank,
  authorityRank,
} from "./authority";
export {
  ADOPTION_SUBJECT_BOUND,
  BALANCE_PROJECTION_RELEASE,
  buildBalanceProjection,
  DISJOINT_ACCOUNTS_POLICY,
  KNOWN_ASSETS_POLICY,
  knownAssetMetricIds,
  type DerivedScopeRelation,
  type EntityRelationRow,
  type EvidenceRef,
  PROJECTION_STATES,
  type ProjectionBuild,
  type ProjectionCandidate,
  type ProjectionInputManifest,
  type ProjectionInputs,
  type ProjectionRow,
  type ProjectionState,
  projectionInputManifest,
  SCOPE_RELATION_RELEASE,
  SUBJECT_STATUSES,
  type SubjectStatus,
  scopeRelationsFromEntityRelations,
  temporalReferenceFor,
} from "./balance-projection";
export {
  DEFAULT_PROJECTION_PAGE_LIMIT,
  PROJECTION_PAGE_LIMITS,
  type ProjectionPageLimit,
  type ProjectionInputsRow,
  type ProjectionPageRow,
  PROJECTION_INPUTS_SQL,
  SUBTOTAL_ROW_BOUND,
  balanceHistoryKeysetSql,
  projectionCoverageSql,
  projectionLegacyPageSql,
  projectionPageSql,
  projectionSubtotalSql,
} from "./balance-projection-sql";
export {
  type BalanceProjectionReader,
  type BalanceSnapshotRow,
  type ProjectionCoverageRow,
  type SubtotalRow,
  createBalanceProjectionReader,
} from "./balance-projection-reader";
export {
  conversionOffer,
  CONVERSION_OFFERS_SQL,
  createRewardReader,
  CURRENT_REWARD_BUCKETS_SQL,
  expiryRule,
  EXPIRY_RULES_SQL,
  membershipState,
  MEMBERSHIP_SQL,
  observedAtValue,
  type Page,
  page,
  QUALIFYING_ACTIVITY_POLICIES,
  rewardBucket,
  rewardProgramOf,
  REWARD_PAGE_LIMIT,
  REWARD_READ_RELEASE,
  type RewardHoldingView,
  type RewardReader,
} from "./rewards";
export {
  ACTIVITY_BASES,
  type ActivityBasis,
  activityEventsSql,
  type AllocationView,
  type BasisTotal,
  basisTotals,
  createEventsReader,
  eventAllocationsSql,
  eventDerivedLegsSql,
  eventLegsSql,
  EVENTS_POLICY_RELEASE,
  type EventsReader,
  type EventsReaderOptions,
  type EventView,
  evidenceLocatorsSql,
  isActivityBasis,
  type LegView,
  obligationSettlementsSql,
  obligationsSql,
  type ObligationView,
  type ReconciliationSignal,
  reportedBalancesSql,
  type SettlementView,
  storedQuantity,
} from "./events";
