interface Env {
  RAW_EVIDENCE_TOKEN: string;
  RAW_EVIDENCE_TOKEN_SBI_VC: string;
  RAW_EVIDENCE_TOKEN_SONY: string;
  RAW_EVIDENCE_TOKEN_SBI_SHINSEI: string;
  RAW_EVIDENCE_TOKEN_MOBILE_SUICA: string;
  RAW_EVIDENCE_TOKEN_GLOBAL_PASS: string;
  GLOBAL_PASS_LEGACY_EMPTY_SHA256_ALLOWLIST: string;
  RAW_EVIDENCE_TOKEN_MYJCB: string;
  RAW_EVIDENCE_TOKEN_VPOINT: string;
  RAW_EVIDENCE_TOKEN_SMBC_DIRECT: string;
  ORIGIN_FINGERPRINT_KEY: string;
}
