// Generated by scripts/parser-digests.ts. Do not edit by hand.
//
// `codeDigest` is the build identity of a parser: SHA-256 over the canonical
// list of its own module and every local module it transitively imports, with
// each file's own SHA-256. Migration 0028 refuses to register the same
// parser name and version with a different digest, and
// test/parser-digests.test.ts fails when this file no longer matches the
// sources it describes.
import type { ParserDigests } from "../../scripts/parser-digests.ts";

export const PARSER_DIGESTS: ParserDigests = {
  sourceDigests: {
    "packages/domain/src/coverage.ts":
      "d3444ac617de5c63c31f6ee2fd9e8eda19daa3a7a28880566c2d97ed34bf8c57",
    "packages/domain/src/guards.ts":
      "5b40a5fb92a270668fbc3e9053e84af0d990c16d5873934e125b1e9822aa4fc9",
    "poc/observation-pipeline/src/money.ts":
      "abdc4ec01a822393810025e3fd2476e47d469f9ad3add42829237b2fecc1ef84",
    "poc/observation-pipeline/src/parsers/coverage.ts":
      "eb7d778cc33f2b0ce41ddcf1352dfdc1be2940b04bcbe61125fdacf911b30742",
    "poc/observation-pipeline/src/parsers/global-pass-activity-parser.ts":
      "3d7af7b4650168811c424f69c7a76cf21ee2c2a04d278064a80a9c7f2e8df74a",
    "poc/observation-pipeline/src/parsers/global-pass-activity.ts":
      "42393618d30efce565baa2ebfc9fbe878bbfe6e21e6a3e80491f661619e5a4cf",
    "poc/observation-pipeline/src/parsers/mobile-suica-sf-history.ts":
      "d6233b8bb03b0a653d4c8c1016d29079635f54811c1176d287a2490330e496b9",
    "poc/observation-pipeline/src/parsers/moneyforward-parser.ts":
      "9ff15fc630314c798312a9d39872bbeb88872a03e83a464abf53446eff373108",
    "poc/observation-pipeline/src/parsers/moneyforward.ts":
      "4f416ffcee43ae0425a5597adefd33636d2a8e8b3ab103c00b95d0603d4bb2f8",
    "poc/observation-pipeline/src/parsers/myjcb.ts":
      "cbcedc7b91084e9bfee2b9e8a8021e9052cd7d42b5af89233473c28ca5293f86",
    "poc/observation-pipeline/src/parsers/paypay-csv.ts":
      "a89829e4856c7baa3abcda2e25762b7debf4a22fddc777756adb920ed8951621",
    "poc/observation-pipeline/src/parsers/sbi-account-assets-current.ts":
      "dabbee389a0f4b7d985ebc302d046c3468065d87d3048fa172f243ac1bff19f7",
    "poc/observation-pipeline/src/parsers/sbi-domestic-cash-positions.ts":
      "0c38ac111de5a5a6416f45f39232e7a93c698cb0a2ed711aa09996f58b225322",
    "poc/observation-pipeline/src/parsers/sbi-domestic-trade-records.ts":
      "9c8489ad2192e6578ab960d74d95f82e825f363528457fb141b7dc6fa7a51478",
    "poc/observation-pipeline/src/parsers/sbi-foreign-cash-balances.ts":
      "535776db124477f9d18e2bd59dd5332c2c30a85e90de9677702f53a70c5aa59d",
    "poc/observation-pipeline/src/parsers/sbi-foreign-cash-positions.ts":
      "e7d26122534728665d274a62a99d46cd541ae39e5817ea1c39252c059f3c2fc7",
    "poc/observation-pipeline/src/parsers/sbi-foreign-trade-records.ts":
      "af02593d61d6d7f1ab2e371d94cd47a9584bd4fb202715e32e079d8c2cef1d95",
    "poc/observation-pipeline/src/parsers/sbi-shinsei-common.ts":
      "e9d08f2520bd293d5b4bd4656af8bb318fba01143734a1fd01bafb0a5ce5781f",
    "poc/observation-pipeline/src/parsers/sbi-shinsei-top-balances-and-activity.ts":
      "eea066c34497d0b6dcbaf7f643dc7e2075a545078acdbe4f49ab6c30fbdd8922",
    "poc/observation-pipeline/src/parsers/sbi-shinsei-yen-deposit-account.ts":
      "86c4e7dca76273133fdd92ade7e95811303de54b74df27f5f8052ebb16dee44f",
    "poc/observation-pipeline/src/parsers/sbi-strict.ts":
      "4e9d1d18fb245ec195703c709fa5e380303f639aeb00fc6df05db09f44985abb",
    "poc/observation-pipeline/src/parsers/sbi-vc-account-margin.ts":
      "9ac2a9a144cef635e384de45700dfcaf423472bf0038dfe1e37076297882da74",
    "poc/observation-pipeline/src/parsers/sbi-vc-cash-balances.ts":
      "9bcf349102da0fcf6edbef9398776c8270726f3120cee2cb6e2f1e4b6507d7ac",
    "poc/observation-pipeline/src/parsers/sbi-vc-cashflows.ts":
      "91db33cc51a5145bbf4b66f2f2c1ca1c035cbbe3ec140b79ea7fb9c259c880e9",
    "poc/observation-pipeline/src/parsers/sbi-vc-common.ts":
      "5f397ff8c09b17f11b26700a8b2c741685d4f3e565c32e29dacd086ac6317a1d",
    "poc/observation-pipeline/src/parsers/sbi-vc-executions.ts":
      "fcc0857c20b31c75c921b2d3ec068f9732ade58eb8a455483b6ef0ba812f447f",
    "poc/observation-pipeline/src/parsers/sbi-vc-position-summary.ts":
      "24ecb7343fdadbe8f5a786b1d5c6399a95b650acadff19abf0a148adfe8511ff",
    "poc/observation-pipeline/src/parsers/sbi-yen-detail-history.ts":
      "1c250eb3217c6e6cadaa2dd4d9dcef559d5d4bd61ec8e76671ea4f575995958b",
    "poc/observation-pipeline/src/parsers/smbc-direct.ts":
      "7ecebf37d5d5558e998d8e76b82df929210f3034abdd726f91d3a8d901ed52a6",
    "poc/observation-pipeline/src/parsers/sony-bank.ts":
      "6c198e41f78003be8f6f1074c28f78721b5cfb2fb031392c91d62ae2ec9a3ee4",
    "poc/observation-pipeline/src/parsers/util.ts":
      "c4ff4a29911701d82be082bbe572be0c70cfb665534aa503a133cda7e4542e3d",
    "poc/observation-pipeline/src/parsers/v-point-pay.ts":
      "c49e01c1ab5d633ab45cb0fcff9fbc5f5ebc81b7a226a08e578c67afcab818f6",
    "poc/observation-pipeline/src/parsers/v-point.ts":
      "1ff35488c84fa1ca373983cbdac3cbcae5c66ebfbf569da4ee5f8d7acc9977fb",
    "poc/observation-pipeline/src/parsers/vpass.ts":
      "c38e30ea809632470ee7c1ed80d542c1beec4d9920f55ed458967f3ff0d202d4",
    "poc/observation-pipeline/src/types.ts":
      "788f30258f5b92a28cd4f806d167d4bb816173e58b6103f277c9787d197e7bf7",
  },
  releases: {
    "global-pass-activity": {
      version: "1.0.0",
      codeDigest: "11f93f326e96962aae4942054c57335c46cbda401baeeba45d0b17ad1f938278",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/global-pass-activity-parser.ts",
        "poc/observation-pipeline/src/parsers/global-pass-activity.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "mobile-suica-sf-history": {
      version: "1.0.0",
      codeDigest: "e50b30a61a78d710cda73d76cf057fd4c40da8b62740806ef21ff5fa1741f3ff",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/mobile-suica-sf-history.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "moneyforward-canonical-evidence-boundary": {
      version: "1.0.1",
      codeDigest: "82bcd353211a7287bbb0239c19c16756f285866f5feba884b3444a7239891d57",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/moneyforward-parser.ts",
        "poc/observation-pipeline/src/parsers/moneyforward.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "moneyforward-monthly-transactions": {
      version: "2.0.2",
      codeDigest: "82bcd353211a7287bbb0239c19c16756f285866f5feba884b3444a7239891d57",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/moneyforward-parser.ts",
        "poc/observation-pipeline/src/parsers/moneyforward.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "myjcb-canonical-evidence-boundary": {
      version: "1.0.0",
      codeDigest: "709807ab7a3957202f2728f63f2519ca525ed208b292fa9df28c70d262a58df2",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/myjcb.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "myjcb-credit-ledger": {
      version: "1.0.0",
      codeDigest: "709807ab7a3957202f2728f63f2519ca525ed208b292fa9df28c70d262a58df2",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/myjcb.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "myjcb-credit-past-month-balances": {
      version: "1.0.0",
      codeDigest: "709807ab7a3957202f2728f63f2519ca525ed208b292fa9df28c70d262a58df2",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/myjcb.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "paypay-csv": {
      version: "0.2.0",
      codeDigest: "de25da7b1c16f88a75f4586a3226ea78030cd93f958206f48df60b69ad0bfbf5",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/paypay-csv.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-account-assets-current": {
      version: "1.0.0",
      codeDigest: "f54b21254d213c165b810d834ba1464c2796c95f8d506ee5a813373a985ab3bb",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-account-assets-current.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-domestic-cash-positions": {
      version: "1.0.1",
      codeDigest: "fd15965bdb755d16802997da4dfe656ff31a4421f9d13e476ce6491ee58910ff",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-domestic-cash-positions.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-domestic-trade-records": {
      version: "0.2.0",
      codeDigest: "3ed3902819a62eaf3880ae4c6286362dde22b36706a3f0e0c0d0e49e42e03d6a",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-domestic-trade-records.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-foreign-cash-balances": {
      version: "0.2.0",
      codeDigest: "929eeaf00a4e39831671f6b584ff89a91f43a6c3b87bde672900069d217975d1",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-foreign-cash-balances.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-foreign-cash-positions": {
      version: "0.3.0",
      codeDigest: "09a417e4664f08c219e64a0db7bb924083d1172f3f12dec79f7e1deb96850015",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-foreign-cash-positions.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-foreign-trade-records": {
      version: "1.0.0",
      codeDigest: "11ee6955a3c9eaa1eca0fb58ed2d5a3cb17195f64ffcb923e914ca07ef1a40e2",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-foreign-trade-records.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-shinsei-top-balances-and-activity": {
      version: "0.1.1",
      codeDigest: "2b730c9c22ee2452c79347c1f3c92646bbb528f7abe3b742328132547bc0bed4",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-shinsei-common.ts",
        "poc/observation-pipeline/src/parsers/sbi-shinsei-top-balances-and-activity.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-shinsei-yen-deposit-account": {
      version: "0.1.1",
      codeDigest: "34f510946996267dd9c89318c4744eec0e9e9d47b131e8e116f8b8bc48d85690",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-shinsei-common.ts",
        "poc/observation-pipeline/src/parsers/sbi-shinsei-yen-deposit-account.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-vc-account-margin": {
      version: "0.2.0",
      codeDigest: "5ba40f8ccefde687589e79933da9285bcbac86d9aa7a31ac2472f24be596303f",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-account-margin.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-common.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-vc-cash-balances": {
      version: "0.2.0",
      codeDigest: "9ff5de971f9321542f68537d4deb2aa21a095f4e4d2dc8f7ca5eadb06219ea96",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-cash-balances.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-common.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-vc-cashflows": {
      version: "0.2.0",
      codeDigest: "5ae8cdd153fab930ee0c12252c4821e8421b9054ab608d9dffd7ec1e24caaa84",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-cashflows.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-common.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-vc-executions": {
      version: "0.2.0",
      codeDigest: "9a8fa02e8180bd3c0d0a768329fd3208b6ad764a348af49c962f27a386d9bb24",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-common.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-executions.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-vc-position-summary": {
      version: "0.2.0",
      codeDigest: "ca0bf337ee5d67d4b3c0a665c505467d7775136c4e89180db3394f9dcc92ad0e",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-common.ts",
        "poc/observation-pipeline/src/parsers/sbi-vc-position-summary.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sbi-yen-detail-history": {
      version: "1.0.2",
      codeDigest: "d8d8d21f3367edfb7bfb47103014338916892fb4b5fbb3bcfbcd3944bbaac9f7",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/sbi-yen-detail-history.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "smbc-direct-balance": {
      version: "1.0.0",
      codeDigest: "c4c594eb751e523ede6b8c9cba9078df7ca5dd9b5a3baf122b2514a9e573ce8c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/smbc-direct.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "smbc-direct-transactions": {
      version: "1.0.0",
      codeDigest: "c4c594eb751e523ede6b8c9cba9078df7ca5dd9b5a3baf122b2514a9e573ce8c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/smbc-direct.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sony-bank-gross-balance": {
      version: "1.0.1",
      codeDigest: "36dc34bc89f73c4635f21a110259f143b111c1ca082266cbf821cb22958ed46c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/sony-bank.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sony-bank-history-csv": {
      version: "1.0.1",
      codeDigest: "36dc34bc89f73c4635f21a110259f143b111c1ca082266cbf821cb22958ed46c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/sony-bank.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sony-bank-history-json": {
      version: "1.0.0",
      codeDigest: "36dc34bc89f73c4635f21a110259f143b111c1ca082266cbf821cb22958ed46c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/sony-bank.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "sony-bank-wallet-history": {
      version: "1.0.2",
      codeDigest: "36dc34bc89f73c4635f21a110259f143b111c1ca082266cbf821cb22958ed46c",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/coverage.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/sony-bank.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "v-point-balance-info": {
      version: "1.0.0",
      codeDigest: "c9432389d9e5710f8b7cbe1ecb9e72456235fba1e1f26692b8b8efc16ef9b72d",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/parsers/v-point.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "v-point-history-page": {
      version: "1.0.0",
      codeDigest: "c9432389d9e5710f8b7cbe1ecb9e72456235fba1e1f26692b8b8efc16ef9b72d",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/parsers/v-point.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "v-point-pay-notification-event": {
      version: "1.0.0",
      codeDigest: "472c8eb48822b7712eca5a21b790643631bb556ba9c5b2a92801f35f69c42676",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/parsers/v-point-pay.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "v-point-smfg-point": {
      version: "1.0.0",
      codeDigest: "c9432389d9e5710f8b7cbe1ecb9e72456235fba1e1f26692b8b8efc16ef9b72d",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/parsers/v-point.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
    "vpass-statement-page": {
      version: "1.0.0",
      codeDigest: "28a54a13875f321092f74b056e4424ced2f248130ee6051484cb50a822766a1e",
      sources: [
        "packages/domain/src/coverage.ts",
        "packages/domain/src/guards.ts",
        "poc/observation-pipeline/src/money.ts",
        "poc/observation-pipeline/src/parsers/sbi-strict.ts",
        "poc/observation-pipeline/src/parsers/util.ts",
        "poc/observation-pipeline/src/parsers/vpass.ts",
        "poc/observation-pipeline/src/types.ts",
      ],
    },
  },
};

/** Parser name -> build digest, the value `parser_releases.code_digest` stores. */
export const PARSER_CODE_DIGESTS: Record<string, string> = Object.fromEntries(
  Object.entries(PARSER_DIGESTS.releases).map(([name, release]) => [name, release.codeDigest]),
);
