-- GENERATED by scripts/config-bootstrap.ts from config/ingest-clients.json.
-- Do not edit: change the declaration and run `mise run bootstrap:ingest-clients`.
--
-- Idempotent: every INSERT is conditional on its own absence and every UPDATE
-- converges one `active` flag, so applying this file twice changes nothing.
-- It is applied by an operator, never by a migration (docs/processor.md §10).

-- ingest client processor-shared-r2
INSERT INTO ingest_clients (id, display_name, active)
SELECT 'processor-shared-r2', 'Processor shared-R2 registration (in-process, U08)', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_clients WHERE id = 'processor-shared-r2');
UPDATE ingest_clients SET active = 1
WHERE id = 'processor-shared-r2' AND active <> 1;
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-mobile-suica', 'collector', 'Shared-R2 collector collector-mobile-suica'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-mobile-suica');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-mobile-suica'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-mobile-suica');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-moneyforward-me', 'collector', 'Shared-R2 collector collector-moneyforward-me'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-moneyforward-me');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-moneyforward-me'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-moneyforward-me');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-myjcb', 'collector', 'Shared-R2 collector collector-myjcb'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-myjcb');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-myjcb'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-myjcb');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-prestia-globalpass', 'collector', 'Shared-R2 collector collector-prestia-globalpass'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-prestia-globalpass');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-prestia-globalpass'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-prestia-globalpass');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-sbi-securities', 'collector', 'Shared-R2 collector collector-sbi-securities'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-sbi-securities');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-sbi-securities'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-securities');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-sbi-shinsei', 'collector', 'Shared-R2 collector collector-sbi-shinsei'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-sbi-shinsei');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-sbi-shinsei'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-shinsei');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-sbi-vc-trade', 'collector', 'Shared-R2 collector collector-sbi-vc-trade'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-sbi-vc-trade');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-sbi-vc-trade'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-vc-trade');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-smbc-direct', 'collector', 'Shared-R2 collector collector-smbc-direct'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-smbc-direct');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-smbc-direct'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-smbc-direct');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-sony-bank', 'collector', 'Shared-R2 collector collector-sony-bank'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-sony-bank');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-sony-bank'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sony-bank');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-v-point', 'collector', 'Shared-R2 collector collector-v-point'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-v-point');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-v-point'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-v-point-pay', 'collector', 'Shared-R2 collector collector-v-point-pay'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-v-point-pay');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-v-point-pay'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-v-point-pay-email', 'collector', 'Shared-R2 collector collector-v-point-pay-email'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-v-point-pay-email');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-v-point-pay-email'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay-email');
INSERT INTO producers (id, kind, display_name)
SELECT 'collector-vpass', 'collector', 'Shared-R2 collector collector-vpass'
WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id = 'collector-vpass');
INSERT INTO ingest_client_producers (ingest_client_id, producer_id)
SELECT 'processor-shared-r2', 'collector-vpass'
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_producers
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-vpass');
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-mobile-suica', 'mobile-suica'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-mobile-suica' AND source_id = 'mobile-suica');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-mobile-suica', 'mobile-suica', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-mobile-suica' AND source_id = 'mobile-suica');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-mobile-suica' AND source_id = 'mobile-suica' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-moneyforward-me', 'moneyforward-me'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-moneyforward-me' AND source_id = 'moneyforward-me');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-moneyforward-me', 'moneyforward-me', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-moneyforward-me' AND source_id = 'moneyforward-me');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-moneyforward-me' AND source_id = 'moneyforward-me' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-myjcb', 'myjcb'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-myjcb' AND source_id = 'myjcb');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-myjcb', 'myjcb', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-myjcb' AND source_id = 'myjcb');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-myjcb' AND source_id = 'myjcb' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-prestia-globalpass', 'global-pass'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-prestia-globalpass' AND source_id = 'global-pass');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-prestia-globalpass', 'global-pass', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-prestia-globalpass' AND source_id = 'global-pass');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-prestia-globalpass' AND source_id = 'global-pass' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-sbi-securities', 'sbi-securities'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-sbi-securities' AND source_id = 'sbi-securities');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-sbi-securities', 'sbi-securities', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-securities' AND source_id = 'sbi-securities');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-securities' AND source_id = 'sbi-securities' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-sbi-shinsei', 'sbi-shinsei-bank'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-sbi-shinsei' AND source_id = 'sbi-shinsei-bank');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-sbi-shinsei', 'sbi-shinsei-bank', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-shinsei' AND source_id = 'sbi-shinsei-bank');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-shinsei' AND source_id = 'sbi-shinsei-bank' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-sbi-vc-trade', 'sbi-vc-trade'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-sbi-vc-trade' AND source_id = 'sbi-vc-trade');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-sbi-vc-trade', 'sbi-vc-trade', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-vc-trade' AND source_id = 'sbi-vc-trade');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sbi-vc-trade' AND source_id = 'sbi-vc-trade' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-smbc-direct', 'smbc-bank'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-smbc-direct' AND source_id = 'smbc-bank');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-smbc-direct', 'smbc-bank', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-smbc-direct' AND source_id = 'smbc-bank');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-smbc-direct' AND source_id = 'smbc-bank' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-sony-bank', 'sony-bank'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-sony-bank' AND source_id = 'sony-bank');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-sony-bank', 'sony-bank', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sony-bank' AND source_id = 'sony-bank');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-sony-bank' AND source_id = 'sony-bank' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-v-point', 'v-point'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-v-point' AND source_id = 'v-point');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-v-point', 'v-point', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point' AND source_id = 'v-point');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point' AND source_id = 'v-point' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-v-point-pay', 'v-point-pay'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-v-point-pay' AND source_id = 'v-point-pay');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-v-point-pay', 'v-point-pay', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay' AND source_id = 'v-point-pay');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay' AND source_id = 'v-point-pay' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-v-point-pay-email', 'v-point-pay'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-v-point-pay-email' AND source_id = 'v-point-pay');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-v-point-pay-email', 'v-point-pay', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay-email' AND source_id = 'v-point-pay');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-v-point-pay-email' AND source_id = 'v-point-pay' AND active <> 1;
INSERT INTO producer_sources (producer_id, source_id)
SELECT 'collector-vpass', 'vpass'
WHERE NOT EXISTS (SELECT 1 FROM producer_sources WHERE producer_id = 'collector-vpass' AND source_id = 'vpass');
INSERT INTO ingest_client_routes (ingest_client_id, producer_id, source_id, active)
SELECT 'processor-shared-r2', 'collector-vpass', 'vpass', 1
WHERE NOT EXISTS (SELECT 1 FROM ingest_client_routes
  WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-vpass' AND source_id = 'vpass');
UPDATE ingest_client_routes SET active = 1
WHERE ingest_client_id = 'processor-shared-r2' AND producer_id = 'collector-vpass' AND source_id = 'vpass' AND active <> 1;
