// The views in 0024 are the single SQL normalization policy. Inline that policy
// over NEW for triggers: filtering the aggregate view would scan all history.
// Keep whitespace around CASE/END: Wrangler's SQL splitter tokenizes these keywords.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const path = fileURLToPath(new URL("../../../packages/storage-d1/migrations/core/0024_observation_decimals.sql", import.meta.url));
const sql = readFileSync(path, "utf8");
function view(name: string): string {
  const marker = `CREATE VIEW ${name} AS\n`;
  const start = sql.indexOf(marker);
  if (start < 0) throw new Error(`missing_view:${name}`);
  const bodyStart = start + marker.length;
  return sql.slice(bodyStart, sql.indexOf(";", bodyStart));
}
const candidates = view("observation_decimal_candidates_v1");
const projection = view("observation_decimal_projection_v1");
const startMarker = "-- New observations are normalized";
const endMarker = "-- Backfill all historical";
const triggers = ["balance", "transaction", "position", "valuation"]
  .map((kind) => {
    const input = `SELECT '${kind}' AS kind,NEW.id AS observation_id,NEW.parse_run_id,${kind === "position" ? "NULL" : "NEW.amount_minor"} AS amount_minor,${kind === "position" ? "NEW.quantity_text" : "NEW.amount_text"} AS amount_text,${kind === "position" ? "NULL" : kind === "balance" ? "NEW.instrument" : "NEW.currency"} AS unit`;
    const rowCandidates = candidates.replace(
      "FROM observation_decimal_inputs_v1",
      `FROM (${input})`,
    );
    const rowProjection = projection.replace(
      "FROM observation_decimal_candidates_v1",
      `FROM (${rowCandidates})`,
    );
    return `CREATE TRIGGER ${kind}_decimals_v1 AFTER INSERT ON ${kind}_observations BEGIN\n INSERT INTO observation_decimal_values\n${rowProjection};\nEND;`;
  })
  .join("\n\n");
const begin = sql.indexOf(startMarker),
  end = sql.indexOf(endMarker);
if (begin < 0 || end <= begin) throw new Error("missing_trigger_markers");
const next =
  sql.slice(0, begin) +
  `${startMarker} in the insertion transaction.\n-- Generated by scripts/generate-decimal-triggers.ts; only NEW is read.\n${triggers}\n\n` +
  sql.slice(end);
if (process.argv.includes("--check")) {
  if (next !== sql) throw new Error("decimal_trigger_generation_drift");
} else writeFileSync(path, next);
